language: node_js
node_js:
  - "6"
script: cd react-performstagram && npm install && npm test && npm run build
after_script:
  - firebase deploy --token $FIREBASE_TOKEN
  - GIT_TOKEN=$GIT_TOKEN WEBPAGETEST_API_KEY=$WEBPAGETEST_API_KEY node githubscript.js