language: node_js
node_js:
  - "node"
  - "iojs"
  - "6"
  - "5"
script: cd react-performstagram && npm install && npm test
after_script:
  - GIT_TOKEN=$GIT_TOKEN WEBPAGETEST_API_KEY=$WEBPAGETEST_API_KEY node githubscript.js