language: node_js
node_js:
  - "node"
  - "iojs"
  - "6"
  - "5"
script: cd react-performstagram && npm install && npm test
after_script:
  -GIT_TOKEN=gitToken WEBPAGETEST_API_KEY=webpageTestAPIKey node githubscript.js