// COMMENTS ACTION
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';
export const CREATE_COMMENTS_SUCCESS = 'CREATE_COMMENTS_SUCCESS';
export const UPDATE_COMMENTS_SUCCESS = 'UPDATE_COMMENTS_SUCCESS';
export const REMOVE_COMMENTS_SUCCESS = 'REMOVE_COMMENTS_SUCCESS';
export const CREATE_COMMENTS_REQUEST = 'CREATE_COMMENTS_REQUEST';
export const UNLOAD_COMMENTS_SUCCESS = 'UNLOAD_COMMENTS_SUCCESS';