export const INIT_AUTH = 'INIT_AUTH';

// POSTS ACTION
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_ERROR = 'UPDATE_POST_SUCCESS';
export const UNLOAD_POSTS_SUCCESS = 'UNLOAD_POSTS_SUCCESS';
// UPLOAD FILE ACTION
export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_SUCCESS';

// COMMENTS ACTION
export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS';
export const CREATE_COMMENTS_SUCCESS = 'CREATE_COMMENTS_SUCCESS';
export const UPDATE_COMMENTS_SUCCESS = 'UPDATE_COMMENTS_SUCCESS';
export const REMOVE_COMMENTS_SUCCESS = 'REMOVE_COMMENTS_SUCCESS';
export const CREATE_COMMENTS_REQUEST = 'CREATE_COMMENTS_REQUEST';
export const UNLOAD_COMMENTS_SUCCESS = 'UNLOAD_COMMENTS_SUCCESS';

// MODAL UPLOAD DIALOG ACTIONS
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const ADD_FILE = 'ADD_FILE';

// SIGN IN ACTIONS
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';